name = "SignalOperators"
uuid = "4d633899-0529-4c96-b1ed-a77d049c39ef"
authors = ["David Little"]
version = "0.1.0"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
LambdaFn = "fcefd6c4-8de0-11e9-0d15-03bc7c8ec982"
MetaArrays = "36b8f3f0-b776-11e8-061f-1f20094e1fc8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1"

[extras]
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"

[targets]
test = ["Test", "WAV","FixedPointNumbers"]
